### ISSUE TITLE
Referenced image data is not handled correctly.

### ISSUE THREAD

**Issue by anotherthomas** [prismicio/scala-kit#31]
Image links (type Link.image) are silently ignored.

**Comment by timoreimann** [comment]
@erwan: Thanks for merging #30. Any plans on making a bugfix release soonish (some time after you've updated the tests)? We currently maintain a local fork of scala-kit that contains @anotherthomas's fix and would like to replace that by a new upstream release.

**Comment by erwan** [comment]
Hi timoreimann,

Yes, we'll release a new version very soon.

**Comment by timoreimann** [comment]
Appreciated, thanks.

**Comment by erwan** [comment]
fixed in 1.3.4
