### ISSUE TITLE
Github releases not up to date

### ISSUE THREAD

**Issue by timoreimann** [prismicio/scala-kit#32]
The [releases tab](https://github.com/prismicio/scala-kit/releases) shows 1.3.0 as the latest release. As of now, however, 1.3.4 seems to have been released already [according to MVN Repository](http://mvnrepository.com/artifact/io.prismic/scala-kit_2.10).

Would be great to see an update to the releases overview.

**Comment by erwan** [comment]
The release tab is up2date.
