### ISSUE TITLE
Missing type property in structured text

### ISSUE THREAD

**Issue by anotherthomas** [prismicio/scala-kit#35]
Both in `block` and `span` the `type`-property is missing.
So e.g. list-items are only identifiable because they have an `ordered`-key.
Italic/bold is not identifiable at all.

**Comment by erwan** [comment]
Hi,

Em and Strong are different classes, you can identify them by pattern matching.

**Comment by lo1tuma** [comment]
The `type` property exists via the REST API, so I would expect feature parity between the scala-kit and the REST API.

**Comment by erwan** [comment]
The API exposes JSON data, and a JSON object is not typed - so we have to precise the type in a field.

In Scala however we have a powerful type system in the language, so it would be redundant to include a field to indicate the type.
